### ISSUE TITLE
Missing Atmosphere script

### ISSUE THREAD

**Issue by vorg** [Fewes/MinimalAtmosphere#2]
The atmosphere object in the scene seems to have missing script. 

> The referenced script on this Behaviour (Game Object 'Atmosphere') is missing!

Should there be something? I'm basically trying to make a sunset and poking around :)

Thanks

**Comment by Fewes** [comment]
Oops, forgot to remove that. Its just an empty script I deleted after I
realized the implementation could be made purely using shaders. Ill remove
the scene ref when Im at my PC tomorrow. Good catch!
